#!/usr/bin/expect -f
set timeout 120
spawn ssh root@157.66.100.35
expect {
    "yes/no" {
        send "yes\r"
        exp_continue
    }
    "password:" {
        send "Topmediacto!!!\r"
        exp_continue
    }
}
expect "#"
send "cd /var/www/topify\r"
expect "#"
send "git status\r"
expect "#"
send "git reset --hard HEAD\r"
expect "#"
send "git pull\r"
expect "#"
send "rm -rf .next\r"
expect "#"
send "npm run build\r"
expect "#"
send "pm2 restart Topify\r"
expect "#"
send "exit\r"
